const loveLines = [
  "I love you — English",
  "Te amo — Spanish",
  "Je t’aime — French",
  "Ich liebe dich — German",
  "Ti amo — Italian",
  "Main tumse pyaar karta hoon — Hindi",
  "Main tumse pyaar karti hoon — Hindi (girl)",
  "Saranghae (사랑해) — Korean",
  "Aishiteru (愛してる) — Japanese",
  "Wo ai ni (我爱你) — Chinese (Mandarin)",
  "Ngo oi nei — Cantonese",
  "Ya tebya lyublyu (Я тебя люблю) — Russian",
  "Eu te amo — Portuguese",
  "Kocham cię — Polish",
  "Volim te — Croatian",
  "Jeg elsker dig — Danish",
  "Jeg elsker deg — Norwegian",
  "Jag älskar dig — Swedish",
  "Ik hou van jou — Dutch",
  "T'estimo — Catalan",
  "Seni seviyorum — Turkish",
  "Ana behibek — Arabic (to female)",
  "Ana behibak — Arabic (to male)",
  "Ngo oi nei — Cantonese",
  "Phom rak khun — Thai (male speaker)",
  "Chan rak khun — Thai (female speaker)",
  "Tôi yêu bạn — Vietnamese",
  "Aku cinta kamu — Indonesian",
  "Mahal kita — Filipino",
  "Ech hob dikh lieb — Yiddish",
  "Mi amas vin — Esperanto",
  "Naan unnai kaadhalikkiren — Tamil",
  "Nenu ninnu premisthunnanu — Telugu",
  "Njan ninne snehikkunnu — Malayalam",
  "Mo nifẹ rẹ — Yoruba",
  "Ke a go rata — Tswana",
  "Ndiyakuthanda — Xhosa",
  "Ek het jou lief — Afrikaans",
  "Inhobok' — Khmer",
  "Ahavti otach — Hebrew (to a girl)",
  "Ahavti otcha — Hebrew (to a boy)",
  "Mwen renmen ou — Haitian Creole",
  "Ngiyakuthanda — Zulu",
  "Ke a go rata — Sesotho",
  "Na-kupenda — Swahili",
  "Mikvarhar — Georgian",
  "Miluji tě — Czech",
  "Szeretlek — Hungarian",
  "Te iubesc — Romanian",
  "Ma armastan sind — Estonian",
  "Es tevi miilu — Latvian",
  "Aš tave myliu — Lithuanian",
  "Lubim ta — Slovak",
  "Ljubim te — Slovenian",
  "Ti voglio bene — Italian (deeply)",
  "I cherish you 💖",
  "You complete me 🥺",
  "You're my everything 💞",
  "Love you infinity ♾️",
  "I love you, my sunshine ☀️",
  "You're the peanut to my butter 🥜",
  "You're my whole heart ❤️",
  "Forever yours 💍",
  "Always and forever 💘",
  "No language can describe it 🌍",
  // You can keep adding more if you like!
];

let i = 0;
const loveText = document.getElementById('loveText');

function showNextLove() {
    loveText.textContent = loveLines[i];
    i = (i + 1) % loveLines.length;
    setTimeout(showNextLove, 1500);
}

showNextLove();
